const themes={
1:{name:'Cascade Executive',label:'Professional, attorney-directed support',headline:'More capacity. Less weight on your shoulders.',blurb:'Dependable paralegal and administrative support that helps Oregon law firms protect attorney time, manage demanding workloads, and keep matters moving.',photo:'assets/cascades-sunrise.webp',photoAlt:'The Cascade Range at sunrise',photoPos:'56% center',logo:'assets/cascade-original-logo-cropped.webp'},
2:{name:'Northwest Counsel',label:'Rooted in Oregon • Built for legal work',headline:'Steady support when your caseload climbs.',blurb:'Flexible paralegal and administrative assistance for Oregon attorneys who need capable help without adding permanent overhead.',photo:'assets/cascades-sunrise.webp',photoAlt:'Snow-capped Cascade mountains above evergreen foothills at sunrise',photoPos:'58% center'},
3:{name:'Rain & River',label:'Professional legal support • Oregon',headline:'Clear support. Confident next steps.',blurb:'Organized, responsive assistance for active matters, overflow work, and the detailed tasks that protect attorney time.',photo:'assets/cascades-river-mist.webp',photoAlt:'A river and evergreen forest beneath misty Cascade mountains',photoPos:'62% center'},
4:{name:'Alpine Minimal',label:'Focused assistance for licensed attorneys',headline:'More capacity. Less to manage.',blurb:'Cascade integrates into your existing workflow with defined scope, clear communication, and dependable delivery.',photo:'assets/cascades-alpine.webp',photoAlt:'A clear snow-covered Cascade peak above an evergreen ridge',photoPos:'60% center'},
5:{name:'High Desert',label:'Oregon-based legal support',headline:'Practical help for a growing practice.',blurb:'Engage Cascade for one assignment, a busy season, or recurring support as your firm’s needs evolve.',photo:'assets/cascades-high-desert.webp',photoAlt:'The Cascade Range viewed across Oregon high desert',photoPos:'58% center'},
6:{name:'Evergreen Practice',label:'Responsive • discreet • attorney-directed',headline:'A dependable extension of your legal team.',blurb:'Professional paralegal and administrative support shaped around your firm, your workflow, and your priorities.',photo:'assets/cascades-river-mist.webp',photoAlt:'Misty Cascade peaks, river, and dense evergreen forest',photoPos:'58% center'},
7:{name:'Cascade Editorial',label:'Cascade Legal Support LLC',headline:'Your practice, supported.',blurb:'Detail-driven assistance for attorneys and law firms that value careful work, responsive communication, and reliable follow-through.',photo:'assets/cascades-alpine.webp',photoAlt:'A crisp alpine view of a snow-covered Cascade mountain',photoPos:'61% center'},
8:{name:'Mount Hood Reflection',label:'Oregon legal support • Clear and dependable',headline:'Clarity for the work that keeps cases moving.',blurb:'Responsive, attorney-directed support for law firms that need careful work, reliable communication, and flexible capacity.',photo:'assets/mount-hood-mirror-lake.webp',photoAlt:'Mount Hood reflected in Mirror Lake, Oregon',photoPos:'58% center'}
};
const n=Number(document.body.dataset.theme||1),t=themes[n];
const logo=t.logo||'assets/cascade-logo-horizontal.png';document.title=`${t.name} | Cascade Legal Support`;
const picker=Object.keys(themes).map(k=>`<a class="${Number(k)===n?'active':''}" href="concept-${k}.html" aria-label="View concept ${k}">${k}</a>`).join('');
document.querySelector('#app').innerHTML=`
<div class="picker" aria-label="Website concepts">${picker}</div>
<div class="topline">Paralegal and administrative support for licensed attorneys and law firms</div>
<header class="site-header"><nav class="wrap"><a class="brand" href="#top"><img src="${logo}" alt="Cascade Legal Support"></a><div class="navlinks"><a href="#services">Services</a><a href="#about">About</a><a href="#josh">Joshua Cook</a><a class="button" href="mailto:josh@cascadelegalsupport.com">Contact Josh</a></div></nav></header>
<main id="top"><section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><div class="eyebrow">${t.label}</div><h1>${t.headline}</h1><p>${t.blurb}</p><div class="actions"><a class="button" href="mailto:josh@cascadelegalsupport.com?subject=Cascade%20Legal%20Support%20Inquiry">Discuss your support needs</a><a class="button secondary" href="#services">Review services</a></div></div><div class="brand-panel photo-panel"><img class="hero-photo" src="${t.photo}" alt="${t.photoAlt}" style="object-position:${t.photoPos}"></div></div></section>
<div class="trust"><div class="wrap trust-grid"><div class="trust-item"><strong>Attorney-directed</strong><span>Paralegal work performed under licensed attorney direction</span></div><div class="trust-item"><strong>Flexible engagement</strong><span>One project, overflow assistance, or recurring support</span></div><div class="trust-item"><strong>Dependable delivery</strong><span>Clear communication and consistent follow-through</span></div></div></div>
<section class="content" id="services"><div class="wrap"><div class="section-head"><div class="eyebrow">Services</div><div><h2>Practical support tailored to your firm.</h2><p>Bring Cascade in for a defined assignment or use us as an ongoing extension of your team as your workload changes.</p></div></div><div class="services"><article class="service"><small>01</small><h3>Document Preparation</h3><p>Careful preparation and formatting aligned with attorney instructions.</p></article><article class="service"><small>02</small><h3>Case File Organization</h3><p>Clear, consistent structures that make case information easier to use.</p></article><article class="service"><small>03</small><h3>Research Summaries</h3><p>Focused research distilled into concise, practical summaries.</p></article><article class="service"><small>04</small><h3>Discovery Support</h3><p>Tracking, organization, and administrative assistance through discovery.</p></article><article class="service"><small>05</small><h3>Administrative Support</h3><p>Reliable help with detailed and time-sensitive legal work.</p></article><article class="service"><small>06</small><h3>Service of Process</h3><p>Professional service and clear communication through completion.</p></article></div></div></section>
<section class="content about" id="about"><div class="wrap about-grid"><div><div class="eyebrow">About Cascade</div><h2>Professional capacity without the full-time commitment.</h2></div><div><p>Cascade Legal Support serves licensed attorneys and law firms that need additional working capacity. Start with a single assignment and develop an ongoing relationship as the need and fit become clear.</p><div class="principles"><div class="principle"><strong>Precision</strong><span>Careful attention to instructions, details, and work product.</span></div><div class="principle"><strong>Responsiveness</strong><span>Clear status and communication throughout the assignment.</span></div><div class="principle"><strong>Reliability</strong><span>Consistent follow-through from scope through completion.</span></div></div></div></div></section>
<section class="profile" id="josh"><div class="wrap profile-grid"><div class="portrait-wrap"><img src="assets/joshua-cook.webp" alt="Joshua Cook, founder of Cascade Legal Support"></div><div class="profile-copy"><div class="eyebrow">Meet the founder</div><h2>Joshua Cook</h2><p class="role">Founder · Cascade Legal Support LLC</p><p>Joshua provides responsive, attorney-directed paralegal and administrative support to law firms that need dependable capacity without adding a full-time position.</p><p>He works closely with each attorney to understand the assignment, follow established workflows, communicate clearly, and carry detailed work through completion.</p><a class="text-link" href="mailto:josh@cascadelegalsupport.com?subject=Cascade%20Legal%20Support%20Inquiry">Contact Joshua <span aria-hidden="true">→</span></a></div></div></section>
<section class="cta"><div class="wrap cta-grid"><div><h2>How can Cascade support your firm?</h2><p>Start with one assignment and see how we work together.</p></div><a class="button" href="mailto:josh@cascadelegalsupport.com?subject=Cascade%20Legal%20Support%20Inquiry">Contact Josh Cook</a></div></section></main>
<footer><div class="wrap"><strong>Important notice:</strong> Cascade Legal Support LLC is not a law firm. Joshua Cook is not an attorney licensed to practice law in Oregon or any other jurisdiction. Cascade provides paralegal and administrative support only and performs all paralegal services under the direction of a licensed attorney.</div></footer>`;
